In [16]:
import numpy as np

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

In [17]:
# Load 10,000 rows of data into the dataframe.
url = "https://www.statlearning.com/s/Advertising.csv"
data = pd.read_csv(url, index_col=0)

data

        TV  radio  newspaper  sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [18]:
y = data['sales']
X = data.drop('sales', axis=1)

X

        TV  radio  newspaper
1    230.1   37.8       69.2
2     44.5   39.3       45.1
3     17.2   45.9       69.3
4    151.5   41.3       58.5
5    180.8   10.8       58.4
..     ...    ...        ...
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

[200 rows x 3 columns]

In [19]:
y

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ...
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: sales, Length: 200, dtype: float64

In [20]:
reg = RandomForestRegressor()

reg.fit(X_train, y_train)

reg.feature_importances_

ValueError: Expected 2D array, got 1D array instead:
array=[15.  15.5 11.9  9.2 12.8  6.6 20.7  6.7 11.2  9.5 10.7  8.8 14.9 17.1
 15.9 15.9 15.  20.7 11.7 21.8  9.3 14.2 10.6 17.3  9.9 15.2 13.3 25.4
 10.8 24.2  5.6 19.2 23.8 17.4 17.4 17.3 12.9 11.8 15.9 15.5 12.9  9.6
 20.1 10.3 19.8 11.4  8.6 15.7 14.1 13.2  8.  22.1 25.5 19.  18.3 15.2
 18.   8.5 18.  18.9 16.6  5.3  3.2 15.3 12.  15.5 17.6 25.4 12.3 21.5
 17.1 23.2 11.5 15.6 12.9  9.6 18.5 19.2 21.2 19.6 10.5 11.8 22.6  9.7
 11.8  9.5 13.2 13.4  7.3 13.6 20.2 12.2 16.7  4.8  9.7 18.4 14.5 12.7
 24.4  8.8 27.  10.8 12.2 26.2 14.  20.2  8.7 11.4  9.7 23.8 14.8 12.9
 12.5 13.2 14.4  5.9  9.7 14.7 10.1 19.6 10.4 22.6 10.1  1.6 11.6 14.7
 17.2 12.2 16.  17.   7.  13.4 18.  15.9 12.4  7.2 19.  19.4 12.6 14.8].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.