In [10]:
import pandas as pd
import sklearn

from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split

from tensorflow import keras
from tensorflow.keras import layers

dat = datasets.load_digits()

digits = pd.DataFrame(dat['data'])

digits['digit'] = dat['target']
digits

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,digit
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0,9
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0,0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0,8
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0,9
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0,8

In [18]:
y = digits['digit']
X = digits.drop('digit', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [43]:
input_shape = X.shape[1]

model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Dense(10, activation='relu'),
            layers.Dense(64, activation='relu'),
            layers.Dense(24, activation='relu'),
            layers.Dense(24, activation='relu'),
            layers.Dense(10, activation='softmax') # This states that the highest probability classification gets chosen as the correct
        ])

In [55]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_5 (Dense)              (None, 10)                650
_________________________________________________________________
dense_6 (Dense)              (None, 64)                704
_________________________________________________________________
dense_7 (Dense)              (None, 24)                1560
_________________________________________________________________
dense_8 (Dense)              (None, 24)                600
_________________________________________________________________
dense_9 (Dense)              (None, 10)                250
=================================================================
Total params: 3,764
Trainable params: 3,764
Non-trainable params: 0
_________________________________________________________________

In [56]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [57]:
batch_size = 128
epochs = 1000

#callback = keras.callbacks.EarlyStopping(monitor='val_loss', patience=10)

model.fit(X_train, y_train, batch_size=batch_size, validation_split=0.25)

8/8 [==============================] - 0s 22ms/step - loss: 2.8131 - accuracy: 0.0945 - val_loss: 2.3284 - val_accuracy: 0.1206