In [1]:
import pandas as pd

In [2]:
file = 'Melbourne_housing_FULL.csv'

df = pd.read_csv(file)
df.shape

(34857, 21)

In [3]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [4]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 21.6 MB

In [5]:
df.loc[0:3, :]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0

In [6]:
df.loc[0:3, ['Price', 'Rooms']]

       Price  Rooms
0        NaN      2
1  1480000.0      2
2  1035000.0      2
3        NaN      3

In [7]:
df.loc[(df['Price'] > 1000000) & (df['Rooms'] < 2)]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
400,Armadale,10 William St,1,h,1435000.0,SP,Jellis,8/10/2016,6.3,3143.0,...,2.0,1.0,144.0,107.0,1900.0,Stonnington City Council,-37.85640,145.02280,Southern Metropolitan,4836.0
1812,Brighton,2a Roslyn St,1,h,1775000.0,S,Nick,10/12/2016,11.2,3186.0,...,NaN,NaN,NaN,NaN,NaN,Bayside City Council,NaN,NaN,Southern Metropolitan,10579.0
3446,Coburg,40 Elizabeth St,1,h,1007000.0,SP,Brad,28/08/2016,7.8,3058.0,...,2.0,0.0,807.0,1.0,NaN,Darebin City Council,-37.73730,144.98250,Northern Metropolitan,11204.0
5113,Hampton,136 Thomas St,1,h,2450000.0,S,Buxton,27/11/2016,13.7,3188.0,...,2.0,0.0,994.0,NaN,NaN,Bayside City Council,-37.94000,145.01510,Southern Metropolitan,5454.0
6294,Malvern,13 Euston St,1,h,2605000.0,S,Jellis,22/08/2016,7.4,3144.0,...,NaN,NaN,NaN,NaN,NaN,Stonnington City Council,NaN,NaN,Southern Metropolitan,4675.0
6906,Moonee Ponds,113 Buckley St,1,u,1685000.0,S,Nelson,18/06/2016,6.9,3039.0,...,NaN,NaN,NaN,NaN,NaN,Moonee Valley City Council,-37.75710,144.91670,Western Metropolitan,6232.0
7142,Niddrie,51 Garnet St,1,h,1330000.0,S,Brad,3/12/2016,11.2,3042.0,...,1.0,1.0,846.0,NaN,NaN,Moonee Valley City Council,-37.74670,144.88720,Western Metropolitan,2291.0
7905,Port Melbourne,73 Heath St,1,h,1014000.0,S,Chisholm,26/07/2016,3.8,3207.0,...,1.0,0.0,151.0,NaN,NaN,Melbourne City Council,-37.83500,144.94440,Southern Metropolitan,8648.0
9123,South Melbourne,218 Ferrars St,1,h,1002000.0,S,Marshall,3/12/2016,2.1,3205.0,...,1.0,0.0,84.0,NaN,1912.0,Port Phillip City Council,-37.83320,144.95480,Southern Metropolitan,5943.0
9305,South Yarra,76 Osborne St,1,h,2115000.0,S,Marshall,17/09/2016,3.3,3141.0,...,1.0,1.0,569.0,NaN,NaN,Melbourne City Council,-37.84280,144.99100,Southern Metropolitan,14887.0
9441,Spotswood,408A Melbourne Rd,1,u,1015000.0,S,Douglas,4/03/2017,7.7,3015.0,...,NaN,NaN,NaN,NaN,NaN,Hobsons Bay City Council,NaN,NaN,Western Metropolitan,1223.0
9580,St Kilda,7/17 Herbert St,1,u,1210000.0,PI,Buxton,18/03/2017,6.1,3182.0,...,1.0,1.0,0.0,49.0,1970.0,Port Phillip City Council,-37.87160,144.98280,Southern Metropolitan,13240.0
11004,Aberfeldie,5 Aroona Ct,1,h,1720000.0,PI,Nelson,15/10/2016,9.1,3040.0,...,2.0,1.0,676.0,136.0,1965.0,Moonee Valley City Council,-37.76320,144.89800,Western Metropolitan,1543.0
11175,East Melbourne,6/45 Gipps St,1,u,1015000.0,S,Caine,8/10/2016,1.5,3002.0,...,1.0,1.0,0.0,NaN,NaN,Melbourne City Council,-37.81360,144.98920,Northern Metropolitan,3040.0
12099,Albert Park,13/123 Beaconsfield Pde,1,u,1100000.0,PI,Nelson,8/04/2017,3.3,3206.0,...,1.0,1.0,0.0,64.0,1888.0,Port Phillip City Council,-37.84870,144.95110,Southern Metropolitan,3280.0
12403,Brunswick,286 Barkly St,1,h,1200000.0,S,Barry,22/04/2017,5.2,3056.0,...,1.0,0.0,225.0,NaN,NaN,Moreland City Council,-37.77610,144.95930,Northern Metropolitan,11918.0
12425,Brunswick East,235 Nicholson St,1,h,1185000.0,S,Nicholson,13/05/2017,4.5,3057.0,...,1.0,0.0,365.0,NaN,NaN,Moreland City Council,-37.76670,144.98020,Northern Metropolitan,5533.0
12578,Caulfield North,6/24 Park Cr,1,u,3050000.0,SP,Gary,6/05/2017,8.1,3161.0,...,NaN,NaN,NaN,NaN,NaN,Glen Eira City Council,NaN,NaN,Southern Metropolitan,6923.0
13302,Newport,33 Bunbury St,1,h,1700000.0,S,Jas,20/05/2017,8.4,3015.0,...,1.0,0.0,622.0,NaN,NaN,Hobsons Bay City Council,-37.84970,144.89030,Western Metropolitan,5498.0
13326,Niddrie,20 Rutland St,1,h,1405000.0,S,Barry,29/04/2017,11.2,3042.0,...,1.0,0.0,649.0,NaN,NaN,Moonee Valley City Council,-37.73560,144.87990,Western Metropolitan,2291.0
15435,Balwyn,17 Birdwood St,1,h,2100000.0,PI,hockingstuart,17/06/2017,7.9,3103.0,...,1.0,1.0,678.0,303.0,2016.0,Boroondara City Council,-37.80292,145.06424,Southern Metropolitan,5682.0
16749,Bulleen,43 Robert St,1,h,1310000.0,S,Jellis,27/05/2017,10.8,3105.0,...,1.0,1.0,604.0,NaN,1999.0,Manningham City Council,-37.75981,145.08599,Eastern Metropolitan,4480.0
17663,Moonee Ponds,15 Grandison St,1,h,1425500.0,S,hockingstuart,8/07/2017,6.2,3039.0,...,1.0,1.0,552.0,190.0,NaN,Moonee Valley City Council,-37.76075,144.91927,Western Metropolitan,6232.0
18869,Broadmeadows,39 Blair St,1,h,1100000.0,VB,Stockdale,22/07/2017,14.0,3047.0,...,1.0,1.0,1312.0,NaN,NaN,Hume City Council,-37.68210,144.92773,Northern Metropolitan,4294.0
20754,Prahran,6 Gooch St,1,h,1475000.0,S,Marshall,9/09/2017,4.6,3181.0,...,1.0,4.0,192.0,NaN,NaN,Stonnington City Council,-37.85553,145.00261,Southern Metropolitan,7717.0
26672,Mount Waverley,14 Wingate Av,1,h,1820000.0,SP,LLC,4/11/2017,14.2,3149.0,...,1.0,1.0,919.0,158.0,2017.0,Monash City Council,-37.88090,145.14360,Eastern Metropolitan,13366.0
32130,South Yarra,15/19 Yarra St,1,u,1317500.0,S,Jellis,3/03/2018,2.7,3141.0,...,NaN,NaN,NaN,NaN,NaN,Melbourne City Council,NaN,NaN,Southern Metropolitan,14887.0
32523,Carlton,164 Canning St,1,h,1252000.0,S,Woodards,17/02/2018,1.6,3053.0,...,1.0,1.0,138.0,NaN,NaN,Melbourne City Council,-37.79460,144.97368,Northern Metropolitan,6786.0

In [8]:
df['price_per_sqm'] = df['Price'] / df['Landsize']
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,price_per_sqm
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0,NaN
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0,7326.732673
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0,6634.615385
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0,NaN
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0,10932.835821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0,2495.784148
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0,9061.224490
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0,3204.545455
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0,NaN
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0,4080.000000

In [9]:
df_clean = df[df['Price'].notna() & df['Landsize'].notna() & df['Landsize'] != 0]
df_clean

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,price_per_sqm
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0,7326.732673
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0,6634.615385
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0,10932.835821
5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,1.0,94.0,NaN,NaN,Yarra City Council,-37.79690,144.99690,Northern Metropolitan,4019.0,9042.553191
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,2.0,120.0,142.0,2014.0,Yarra City Council,-37.80720,144.99410,Northern Metropolitan,4019.0,13333.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34851,Yarraville,78 Bayview Rd,3,h,1101000.0,S,Jas,24/02/2018,6.3,3013.0,...,NaN,288.0,NaN,NaN,Maribyrnong City Council,-37.81095,144.88516,Western Metropolitan,6543.0,3822.916667
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0,2495.784148
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0,9061.224490
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0,3204.545455
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0,4080.000000

In [11]:
df_clean.groupby('Suburb')['price_per_sqm'].describe()

,count,mean,std,min,25%,50%,75%,max
Suburb,,,,,,,,
Abbotsford,53.0,7111.149236,3282.906657,254.079254,5198.895028,7135.416667,8945.578231,14950.980392
Aberfeldie,47.0,2901.042948,1424.828007,180.758017,2140.956348,2506.849315,3153.394308,6714.285714
Airport West,93.0,2082.514920,998.413125,742.827869,1340.306834,1545.901639,2837.735849,5157.342657
Albanvale,7.0,1140.225923,352.858679,912.762520,955.356215,995.274102,1129.581341,1903.669725
Albert Park,73.0,11412.408079,3808.070804,955.645161,9281.437126,10901.639344,13507.109005,20476.190476
...,...,...,...,...,...,...,...,...
Wollert,36.0,1600.393215,491.183985,751.121076,1332.945327,1498.175182,1631.783505,3486.956522
Wyndham Vale,21.0,1019.486032,288.981905,646.029610,823.423423,976.562500,1176.470588,1625.482625
Yallambie,28.0,1436.643796,366.400409,920.679887,1214.015152,1330.140872,1698.733544,2706.645057
Yarra Glen,1.0,718.424102,NaN,718.424102,718.424102,718.424102,718.424102,718.424102
Yarraville,182.0,3531.892026,1611.200838,502.893891,2229.321745,3208.175505,4537.411972,10106.382979

In [12]:
df_clean.groupby('Suburb')[['price_per_sqm']].describe().sort_values(('price_per_sqm', 'mean'), ascending=False)

                price_per_sqm                                          \
                        count          mean           std         min
Suburb
Toorak                   56.0  13434.497412  58173.812822  198.088898
Middle Park              42.0  11527.590437   3290.231323  703.947368
Albert Park              73.0  11412.408079   3808.070804  955.645161
Heidelberg West          79.0  10468.967037  79717.408604  702.683616
South Melbourne          82.0  10173.203060   4396.097749  155.668605
...                       ...           ...           ...         ...
Bullengarook              3.0     53.705931     69.626743    7.157513
Wandin North              1.0     28.395062           NaN   28.395062
Gisborne South            2.0     28.169994      7.338175   22.981121
Silvan                    2.0     21.037872      9.562285   14.276316
Wildwood                  1.0     11.569134           NaN   11.569134


                         25%           50%           75%            max
Suburb
Toorak           1889.931741   5694.654632   8587.126931  440000.000000
Middle Park      9576.781388  11614.204652  13305.889567   17875.000000
Albert Park      9281.437126  10901.639344  13507.109005   20476.190476
Heidelberg West  1107.166373   1225.126476   1401.627541  710000.000000
South Melbourne  8197.746884  10507.474626  12428.984558   21234.567901
...                      ...           ...           ...            ...
Bullengarook       13.683897     20.210280     76.980140     133.750000
Wandin North       28.395062     28.395062     28.395062      28.395062
Gisborne South     25.575557     28.169994     30.764431      33.358867
Silvan             17.657094     21.037872     24.418650      27.799428
Wildwood           11.569134     11.569134     11.569134      11.569134

[331 rows x 8 columns]

In [17]:
import numpy as np

df_clean.groupby('CouncilArea')['Price'].agg([np.mean, np.median])

                                        mean     median
CouncilArea
Banyule City Council            9.663514e+05   850000.0
Bayside City Council            1.765558e+06  1615000.0
Boroondara City Council         1.919276e+06  1810000.0
Brimbank City Council           7.010967e+05   680500.0
Cardinia Shire Council          5.724118e+05   559000.0
Casey City Council              7.150813e+05   664750.0
Darebin City Council            9.956350e+05   920000.0
Frankston City Council          7.005316e+05   650000.0
Glen Eira City Council          1.255363e+06  1240000.0
Greater Dandenong City Council  7.459563e+05   740000.0
Hobsons Bay City Council        1.065741e+06   963500.0
Hume City Council               6.089478e+05   600000.0
Kingston City Council           1.030113e+06   975000.0
Knox City Council               9.090392e+05   870000.0
Macedon Ranges Shire Council    7.895385e+05   767500.0
Manningham City Council         1.273675e+06  1245000.0
Maribyrnong City Council        9.084827e+05   875000.0
Maroondah City Council          9.249039e+05   900000.0
Melbourne City Council          1.316467e+06  1200000.0
Melton City Council             5.144119e+05   460000.0
Mitchell Shire Council          4.808750e+05   462500.0
Monash City Council             1.264055e+06  1210000.0
Moonee Valley City Council      1.140750e+06  1051000.0
Moorabool Shire Council         3.823333e+05   412000.0
Moreland City Council           9.446278e+05   860000.0
Nillumbik Shire Council         7.118111e+05   622000.0
Port Phillip City Council       1.556791e+06  1407500.0
Stonnington City Council        1.940833e+06  1677500.0
Whitehorse City Council         1.213547e+06  1140000.0
Whittlesea City Council         6.382102e+05   638500.0
Wyndham City Council            5.675531e+05   541000.0
Yarra City Council              1.255689e+06  1202500.0
Yarra Ranges Shire Council      7.619552e+05   730000.0

In [31]:
df['Landsize'].describe()

count     23047.000000
mean        593.598993
std        3398.841946
min           0.000000
25%         224.000000
50%         521.000000
75%         670.000000
max      433014.000000
Name: Landsize, dtype: float64

In [37]:
# if lower than 25 percentile = small, if lower than 75 = medium, if greater or equal to 75 = large

def recode_landsize(s):
    if np.isnan(s):
        i = 'UNKNOWN'
    elif s < 224:
        i = 'SMALL'
    elif s < 521:
        i = 'MEDIUM'
    else:
        i = 'LARGE'
    
    return i

In [39]:
df['LandSizeCategory'] = df['Landsize'].apply(recode_landsize)

In [41]:
df['LandSizeCategory'].value_counts()

UNKNOWN    11810
LARGE      11527
MEDIUM      5780
SMALL       5740
Name: LandSizeCategory, dtype: int64